# Change these first
owner: zv8001 # Your GitHub organization or username, where this repository lives
repo: EEI-Stats # The name of this repository

sites:
  - name: ZV800.com
    url: https://www.zv800.com//
    maxResponseTime: 1000
    
  - name: EEI API
    url: https://eei-api-533b.netlify.app/
    maxResponseTime: 1000
    
  - name: Main Roblox
    url: https://www.roblox.com/
    maxResponseTime: 1000
    
  - name: Roblox Devform 
    url: https://devforum.roblox.com/
    maxResponseTime: 1000
    
  - name: Roblox Devhub
    url: https://developer.roblox.com
    maxResponseTime: 1000


  - name: Avatar API Endpoint
    url: https://avatar.roblox.com/v1/avatar-rules
    method: GET
    maxResponseTime: 1000


  - name: Badges API Endpoint
    url: https://badges.roblox.com/v1/badges/2124548403
    method: GET
    maxResponseTime: 1000


  - name: Catalog API Endpoint
    url: https://catalog.roblox.com/v1/bundles/details?bundleIds=192
    method: GET
    maxResponseTime: 1000


  - name: Friends API Endpoint
    url: https://friends.roblox.com/v1/metadata
    method: GET
    maxResponseTime: 1000


  - name: Groups API Endpoint
    url: https://groups.roblox.com/v1/groups/5680533
    method: GET
    maxResponseTime: 1000

  - name: Inventory API Endpoint
    url: https://inventory.roblox.com/v1/users/82738847/assets/collectibles?limit=10&sortOrder=Asc
    method: GET
    maxResponseTime: 1000
    
    # fix when roblox stop oopsie

  - name: Thumbnails API Endpoint
    url: https://thumbnails.roblox.com/v1/assets?assetIds=82738847&format=Png&isCircular=false&size=30x30
    method: GET
    maxResponseTime: 1000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /EEI-Stats
  logoUrl: https://images-ext-1.discordapp.net/external/XTUYFFEmesMEIOAwvzFWoMUm6v4tmRaveTY9rml0KDI/https/tr.rbxcdn.com/2ffb2c56800d820039b95b9022d0867b/150/150/Image/Png
  name: EEI Status
  introTitle: "**EEI Stats** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This website is mainly a Roblox monitoring page but also contains some features for EEI developers. This web server is run on GitHub and also powers the global-automated-status in the Extreme Energy Incorporated discord server. This page is entirely powered by uptime [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
