# Change these first
owner: zv8001 # Your GitHub organization or username, where this repository lives
repo: EEI-Stats # The name of this repository

sites:
  - name: ZV800.com
    url: https://www.zv800.com/
  - name: EEI API
    url: https://eei-api-533b.netlify.app/
  - name: Main Roblox
    url: https://www.roblox.com/
  - name: Roblox Devform 
    url: https://devforum.roblox.com/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /EEI-Stats
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: EEI Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
